#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
expand-url

:copyright: (c) 2014 by Alexander Skiba <skiba@icg.tugraz.at>
:licence: MIT
:bugreports: skiba@icg.tugraz.at

Expands a given URL and prints all redirect locations.
Shamelessly borrowed from:
http://www.commandlinefu.com/commands/view/9515/expand-shortened-urls

(also serves as a reminder of how to use subprocess.Popen())
"""

import sys
import subprocess

def main():
    """Expands a given short URL and prints all redirect locations"""
    curl = subprocess.Popen(["curl", "-sIL", sys.argv[1]],
        stdout=subprocess.PIPE)
    result = subprocess.check_output(["grep", "-i", "^Location"],
        stdin=curl.stdout)

    print result.strip()

if __name__ == '__main__':
    main()
